language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work/
    - $TRAVIS_BUILD_DIR/binaryen/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - hvr-ghc
            - llvm-toolchain-trusty
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - ghc-8.0.2

    - os: osx
      osx_image: xcode8.2

before_install:
  - cd $TRAVIS_BUILD_DIR/binaryen
  - git pull || (cd .. && rm -rf binaryen && git clone --depth 1 https://github.com/WebAssembly/binaryen.git && cd binaryen)
  - cmake -DCMAKE_C_COMPILER=`which clang-5.0` -DCMAKE_CXX_COMPILER=`which clang++-5.0` -DCMAKE_INSTALL_PREFIX=~/.local -G Ninja .
  - ninja
  - ninja install

  - cd $TRAVIS_BUILD_DIR
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:/opt/ghc/8.0.2/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - stack config set system-ghc --global true
  - stack config set install-ghc --global true
  - stack --no-terminal build --test --bench --only-dependencies

install: true

script:
  - cd $TRAVIS_BUILD_DIR
  - stack --no-terminal build --haddock --no-haddock-deps --test --bench --no-run-benchmarks
