language: generic

git:
  depth: 1

cache:
  directories:
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          sources:
            - hvr-ghc
            - llvm-toolchain-trusty
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - ghc-8.0.2
            - ninja-build

    - os: osx
      osx_image: xcode8.2

before_install:
  - travis/before_install-`uname`.sh

install: true

script:
  - cd $TRAVIS_BUILD_DIR
  - stack --no-terminal build --haddock --no-haddock-deps --test --bench --no-run-benchmarks
