shallow_clone: true

cache:
  - "%APPDATA%\\stack"
  - "%APPVEYOR_BUILD_FOLDER%\\.stack-work"

install:
  - ps: |
      New-Item $env:APPDATA\\local\\bin -ItemType directory
      $env:PATH="$env:APPDATA\\local\\bin;$env:PATH"
      Invoke-WebRequest https://www.stackage.org/stack/windows-x86_64 -OutFile $env:TMP\\stack.zip
      Expand-Archive $env:TMP\\stack.zip $env:APPDATA\\local\\bin
      stack --no-terminal setup | Out-Null
      stack --no-terminal exec pacman -- -Syu --noconfirm
      stack --no-terminal exec pacman -- -Su --noconfirm
      stack --no-terminal exec pacman -- -Su --noconfirm
      While ($true) { stack --no-terminal build --test --bench --only-dependencies; If ($?) { Break } }

build: off

build_script:
  - ps: stack --no-terminal build --haddock --no-haddock-deps --test --no-run-tests --bench --no-run-benchmarks

test: off

test_script:
  - ps: stack --no-terminal test
