name: blockcat
version: 0.0.1
category: Language
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/blockcat

extra-source-files:
  - README.md
  - CHANGELOG.md

extra-libraries:
  - binaryen

when:
  - condition: os(windows)
    then:
      include-dirs:
        - C:\\msys64\\usr\\local\\include
      extra-lib-dirs:
        - C:\\msys64\\usr\\local\\lib
    else:
      include-dirs:
        - $HOME/.local/include
      extra-lib-dirs:
        - $HOME/.local/lib

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10

library:
  source-dirs: src
