name: blockcat
version: 0.0.1
category: Language
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/blockcat

extra-source-files:
  - README.md
  - CHANGELOG.md

extra-libraries:
  - binaryen

include-dirs:
  - cbits

c-sources:
  - cbits/*.c

cc-options: -std=c11

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10
  - bytestring
  - hashable
  - unordered-containers
  - vector

library:
  source-dirs: src
